version: '3.0'
services:
  lpr-storage:
    image: openjdk:8-jdk-slim
    container_name: lpr-storage-container
    command: java -jar storage-0.0.1.war -m http.server 7070
    ports:
      - 7070:7070
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - environment.env
    network_mode: "host"