server:
  port: ${PORT:6060}

spring:
  application:
    name: ${APP_NAME:lpr-storage}
  profiles:
    active: ${ENVIRONMENT:development}
  data:
    mongodb:
      host: ${MONGODB_HOST:127.0.0.1}
      port: ${MONGODB_PORT:27017}
      authentication-database: ${MONGODB_AUTHENTICATION_DATABASE:admin}
      username: ${MONGODB_USERNAME:takeru}
      password: ${MONGODB_PASSWORD:takeru123}
      database: ${MONGODB_DATABASE_NAME:lpr-storage}
  main:
    allow-bean-definition-overriding: true

storage:
  name: storage
  upload:
    max-file-size: ${MAX_UPLOAD_FILE_SIZE:2000000}