server:
  port: ${PORT:6060}

spring:
  profiles:
    active: ${ENVIRONMENT}
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:20717}
      authentication-database: ${MONGODB_AUTHENTICATION_DATABASE:admin}
      username: ${MONGODB_USERNAME:}
      password: ${MONGODB_PASSWORD:}
      database: ${MONGODB_DATABASE_NAME:lpr-storage}
  main:
    allow-bean-definition-overriding: true

storage:
  name: storage
  upload:
    max-file-size: ${MAX_UPLOAD_FILE_SIZE:2000000}