server:
  port: ${PORT:6060}

spring:
  application:
    name: lpr-storage-service
  profiles:
    active: ${ENVIRONMENT:development}
  data:
    mongodb:
      host: ${MONGODB_HOST:127.0.0.1}
      port: ${MONGODB_PORT:27017}
      authentication-database: ${MONGODB_AUTHENTICATION_DATABASE:admin}
      username: ${MONGODB_USERNAME:takeru}
      password: ${MONGODB_PASSWORD:takeru123}
      database: ${MONGODB_DATABASE_NAME:lpr-storage}
  main:
    allow-bean-definition-overriding: true

storage:
  name: storage
  upload:
    max-file-size: ${MAX_UPLOAD_FILE_SIZE:2000000}
  default-image:
    classpath: classpath:default/images/image_not_available.png
  delete-image-period: ${DELETE_IMAGE_PERIOD:90}
  background-task:
    auto-remove-image:
      fixed-delay: ${BG_TASK_FIXED_DELAY:1800000}
      init-delay: ${BG_TASK_INIT_DELAY:5000}